- name: Install BIND9 packages
  ansible.builtin.apt:
    name:
      - bind9
      - bind9utils
      - bind9-dnsutils
    state: present
    update_cache: true

- name: Deploy named.conf.options
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: "0644"
  notify: restart bind9

- name: Deploy local zone file
  ansible.builtin.template:
    src: db.domain.j2
    dest: "/etc/bind/db.{{ domain_name }}"
    owner: root
    group: bind
    mode: "0644"
  notify: restart bind9

- name: Ensure zone is configured
  ansible.builtin.blockinfile:
    path: /etc/bind/named.conf.local
    block: |
      zone "{{ domain_name }}" {
          type master;
          file "/etc/bind/db.{{ domain_name }}";
      };
    marker: "// {mark} ACDC MANAGED ZONE"
  notify: restart bind9

- name: Ensure bind9 service enabled
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: true
