- name: Install Chrony
  ansible.builtin.apt:
    name:
      - chrony
    state: present
    update_cache: true

- name: Deploy chrony configuration
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart chrony

- name: Ensure chrony service enabled
  ansible.builtin.service:
    name: chrony
    state: started
    enabled: true
